use("test")

// if specified, clear out all existing collections (except the users collection)
if (true) {
   db.volunteers.deleteMany({})
   db.events.deleteMany({})
}

// creates 12 volunteerId variables
for (let i = 1; i <= 12; i++) {
  this[`volunteerId${i}`] = ObjectId();
}

db.volunteers.insertMany([
{
    "firstName" : "Jasmine",
    "lastName" : "Reyes",
    "_id" : "volunteerId1",
    "email" : "JasRey@gmail.com",
    "phone" : "865-123-4567",
    "role" : "Admin",
    "demograhic": {
        "age": "28",
        "race": "African",
        "sex": "Female",
        "income": "73000",
        "zip_code": "37830",
        "occupation": "Physical Therapist"
    }
}, {
    "firstName" : "Liam",
    "lastName" : "Cooper",
    "_id" : "volunteerId2",
    "email" : "Lcoop@outlook.com",
    "phone" : "865-280-3209",
    "role" : "Volunteer",
    "demograhic": {
        "age": "32",
        "race": "White",
        "sex": "Male",
        "income": "65000",
        "zip_code": "37831",
        "occupation": "Electrician"
    }
}, {
    "firstName" : "Maya",
    "lastName" : "Patel",
    "_id" : "volunteerId3",
    "email" : "Maya22@aol.com",
    "phone" : "585-905-2853",
    "role" : "Volunteer",
    "demograhic": {
        "age": "40",
        "race": "Indian",
        "sex": "female",
        "income": "64000",
        "zip_code": "37771",
        "occupation": "Software Developer"
    }
}, {
    "firstName" : "Ethan",
    "lastName" : "Brooks",
    "_id" : "volunteerId4",
    "email" : "broski87@gmail.com",
    "phone" : "256-381-7452",
    "role" : "Volunteer",
    "demograhic": {
        "age": "67",
        "race": "white",
        "sex": "male",
        "income": "",
        "zip_code": "37831",
        "occupation": "Retired"
    }
}, {
    "firstName" : "Zoe",
    "lastName" : "Thompson",
    "_id" : "volunteerId5",
    "email" : "ThompsonBowling@yahoo.com",
    "phone" : "865-213-4827",
    "role" : "Volunteer",
    "demograhic": {
        "age": "38",
        "race": "white",
        "sex": "female",
        "income": "230000",
        "zip_code": "37763",
        "occupation": "Nurse Anesthetist"
    }
}, {
    "firstName" : "Lucas",
    "lastName" : "Ramirez",
    "_id" : "volunteerId6",
    "email" : "lram@gmail.com",
    "phone" : "857-374-1927",
    "role" : "Manager",
    "demograhic": {
        "age": "45",
        "race": "African",
        "sex": "male",
        "income": "72060",
        "zip_code": "37748",
        "occupation": ""
    }
}, {
    "firstName" : "Ava",
    "lastName" : "Mitchell",
    "_id" : "volunteerId7",
    "email" : "Avalmichell@gmail.com",
    "phone" : "820-472-1746",
    "role" : "Volunteer",
    "demograhic": {
        "age": "21",
        "race": "white",
        "sex": "female",
        "income": "",
        "zip_code": "89323",
        "occupation": "College student"
    }
}, {
    "firstName" : "Jackson",
    "lastName" : "Nguyen",
    "_id" : "volunteerId8",
    "email" : "newguy@outlook.com",
    "phone" : "872-742-7452",
    "role" : "Manager",
    "demograhic": {
        "age": "26",
        "race": "chinese",
        "sex": "male",
        "income": "83000",
        "zip_code": "64245",
        "occupation": "Math Professor"
    }
}, {
    "firstName" : "Harper",
    "lastName" : "Carter",
    "_id" : "volunteerId9",
    "email" : "harp@aol.com",
    "phone" : "237-197-1582",
    "role" : "Admin",
    "demograhic": {
        "age": "38",
        "race": "hispanic",
        "sex": "male",
        "income": "650000",
        "zip_code": "37771",
        "occupation": "Neurosurgeon"
    }
}, {
    "firstName" : "Noah",
    "lastName" : "Morgan",
    "_id" : "volunteerId10",
    "email" : "noah@gmail.com",
    "phone" : "370-712-6234",
    "role" : "Volunteer",
    "demograhic": {
        "age": "89",
        "race": "white",
        "sex": "male",
        "income": "8000000",
        "zip_code": "78235",
        "occupation": "Battle Rapper"
    }
}, {
    "firstName" : "Isabella",
    "lastName" : "Khan",
    "_id" : "volunteerId11",
    "email" : "khanacademy@icloud.com",
    "phone" : "513-643-1674",
    "role" : "Manager",
    "demograhic": {
        "age": "43",
        "race": "Russian",
        "sex": "Female",
        "income": "",
        "zip_code": "",
        "occupation": ""
    }
}, {
    "firstName" : "Caleb",
    "lastName" : "Anderson",
    "_id" : "volunteerId12",
    "email" : "caland12@icloud.com",
    "phone" : "433-734-3872",
    "role" : "Volunteer",
    "demograhic": {
        "age": "29",
        "race": "white",
        "sex": "male",
        "income": "40000",
        "zip_code": "37932",
        "occupation": "Painter"
    }
}
])

// creates 5 eventId variables
for (let i = 1; i <= 5; i++) {
  this[`eventId${i}`] = ObjectId();
}

// STANDALONE EVENTS
db.events.insertMany([
  {
    "_id": "eventId1",
    "title": "Market Square",
    "location": "Market Square, Knoxville, TN 37902",
    "day" : "2024-04-10T09:00:00",
    "startTime": "2024-04-10T09:00:00",
    "endTime": "2024-04-10T12:00:00",
    "description": "Handing out seeds for gardens",
    "numVolsNeeded": "15",
    "manager": "volunteerId9"
}, {
    "_id": "eventId2",
    "title": "University of Tennessee",
    "location": "Address: 800 Andy Holt Tower, Knoxville, TN 37996",
    "day" : "2024-05-15T14:30:00",
    "startTime": "2024-05-15T14:30:00",
    "endTime": "2024-05-15T17:30:00",
    "description": "Food market",
    "numVolsNeeded": "30",
    "manager": "volunteerId6"
}, {
    "_id": "eventId3",
    "title": "World's Fair Park",
    "location": "963 World's Fair Park Dr, Knoxville, TN 37916",
    "day" : "2024-06-20T11:45:00",
    "startTime": "2024-06-20T11:45:00",
    "endTime": "2024-06-20T14:45:00",
    "description": "Awareness event",
    "numVolsNeeded": "25",
    "manager": "volunteerId6"
}, {
    "_id": "eventId4",
    "title": "Knox Museum of Art",
    "location": "1050 World's Fair Park Dr, Knoxville, TN 37916",
    "day" : "2024-07-25T08:15:0",
    "startTime": "2024-07-25T08:15:0",
    "endTime": "2024-07-25T08:15:00",
    "description": "Awareness event",
    "numVolsNeeded": "20",
    "manager": "volunteerId9"
}, {
    "_id": "eventId5",
    "title": "The Old City",
    "location": "123 W Jackson Ave Knoxville, TN 37902",
    "day" : "2024-03-30T10:00:00",
    "startTime": "2024-03-30T10:00:00",
    "endTime": "2024-03-30T13:00:00",
    "description": "Seed handout",
    "numVolsNeeded": "18",
    "manager": "volunteerId6"
}
])
